strings = [
	"",
	"Kotemon",
	"Kumamon",
	"Monmon",
	"Agumon",
	"Veemon",
	"Guilmon",
	"Renamon",
	"Patamon",
	"Dinohumon",
	"Hookmon",
	"Grizzmon",
	"Greymon",
	"ExVeemon",
	"Growlmon",
	"Kyubimon",
	"Angemon",
	"Devimon",
	"Stingmon",
	"Angewomon",
	"Kyukimon",
	"Armormon",
	"GrapLeomon",
	"MetalGreymon",
	"SkullGreymon",
	"Paildramon",
	"WarGrowlmon",
	"Taomon",
	"MagnaAngemon",
	"Myotismon",
	"MetalMamemon",
	"Kabuterimon",
	"Digitamamon",
	"GuardiAngemon",
	"Cannondramon",
	"Marsmon",
	"WarGreymon",
	"Imperialdramon",
	"Gallantmon",
	"Sakuyamon",
	"Seraphimon",
	"MetalGarurumon",
	"Rosemon",
	"BK WarGreymon",
	"Imperialdramon-F",
	"MaloMyotismon",
	"MegaGargomon",
	"GranKuwagamon",
	"Phoenixmon",
	"Omnimon",
	"Imperialdramon-P",
	"Beelzemon",
	"Diaboromon",
	"Agunimon",
	"BladeGarurumon",
	"AncientGreymon",
	"a",
	"a",
	"Kunemon",
	"Tapirmon",
	"Crabmon",
	"Gizamon",
	"DemiDevimon",
	"Betamon",
	"Vegiemon",
	"Kuwagamon",
	"Yanmamon",
	"Kiwimon",
	"Dokugumon",
	"Goburimon",
	"Baronmon",
	"Minotarumon",
	"Flymon",
	"Woodmon",
	"Tyrannomon",
	"Triceramon",
	"Airdramon",
	"Gekomon",
	"Coelamon",
	"Bakemon",
	"Phantomon",
	"Kokatorimon",
	"Apemon",
	"Shellmon",
	"Tortomon",
	"Dolphmon",
	"Gesomon",
	"Octomon",
	"Divermon",
	"ShogunGekomon",
	"Seadramon",
	"Mammothmon",
	"Etemon",
	"Ogremon",
	"Tuskmon",
	"Rockmon",
	"Quetzalmon",
	"Vademon",
	"Maildramon",
	"Mamemon",
	"Guardromon",
	"Thundermon",
	"Hagurumon",
	"Clockmon",
	"Andromon",
	"Numemon",
	"Sukamon",
	"Garbagemon",
	"Roachmon",
	"Raremon",
	"Cyclonemon",
	"Megadramon",
	"Monzaemon",
	"Tankmon",
	"Nanimon",
	"Musyamon",
	"Kurisarimon",
	"Snimon",
	"Blossomon",
	"Cherrymon",
	"Gargoylemon",
	"Mummymon",
	"Arukenimon",
	"Okuwamon",
	"MetalTyrannomon",
	"Deltamon",
	"Whamon",
	"MarineDevimon",
	"Dragomon",
	"MegaSeadramon",
	"Ebidramon",
	"Vilemon",
	"SkullSatamon",
	"Brachiomon",
	"Drimogemon",
	"Flarerizamon",
	"Meramon",
	"Mojyamon",
	"Frigimon",
	"Icemon",
	"Giromon",
	"Vikemon",
	"Lynxmon",
	"SkullMeramon",
	"Devidramon",
	"Kimeramon",
	"Pukumon",
	"MetalSeadramon",
	"Tylomon",
	"Scorpiomon",
	"Antylamon",
	"H-Kabuterimon",
	"Puppetmon",
	"SkullMammothmon",
	"Valkyrimon",
	"LadyDevimon",
	"MetalEtemon",
	"KingEtemon",
	"Gryphonmon",
	"Infermon",
	"Shadramon",
	"Boltmon",
	"Piedmon",
	"Machinedramon",
	"VenomMyotismon",
	"Apokarimon",
	"Ghoulmon",
	"Creepymon",
	"Armageddemon",
	"RedVegiemon",
	"Kuwagamon",
	"Yanmamon",
	"Dokugumon",
	"Goburimon",
	"Minotarumon",
	"Flymon",
	"Woodmon",
	"Triceramon",
	"Airdramon",
	"Phantomon",
	"Kokatorimon",
	"Tortomon",
	"ShogunGekomon",
	"Seadramon",
	"Mammothmon",
	"Fugamon",
	"Vademon",
	"Maildramon",
	"Guardromon",
	"Numemon",
	"Numemon",
	"Numemon",
	"Numemon",
	"Numemon",
	"Raremon",
	"Cyclonemon",
	"Tankmon",
	"Musyamon",
	"Kurisarimon",
	"Snimon",
	"Blossomon",
	"Cherrymon",
	"Whamon",
	"MegaSeadramon",
	"Ebidramon",
	"Vilemon",
	"Drimogemon",
	"BlueMeramon",
	"Vikemon",
	"MetalSeadramon",
	"Scorpiomon",
	"Antylamon",
	"Pharaohmon",
	"MasterTyrannomon",
	"Zanbamon",
	"HiAndromon",
	"WaruMonzaemon",
	"Datamon",
	"Knightmon",
	"Bulbmon",
	"Persiamon",
	"Raidenmon",
	"Fujinmon",
	"Suijinmon",
	"Raijinmon",
	"Galacticmon",
	"BK WarGreymon",
	"BK Seraphimon",
	"BK MegaGargomon",
	"BK Imperialdram.",
	"BK WarGrowlmon",
	"BK KingNumemon",
	"MetalGreymon",
	"Paildramon",
	"WarGrowlmon",
	"MagnaAngemon",
	"Taomon",
	"Kyukimon",
	"Armormon",
	"GrapLeomon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Cardmon",
	"Vemmon",
	"Galacticmon",
	"Galacticmon",
]
