strings = [
	"",
	"Put all non-white Digimon\ninto trash can.",
	"Bring 2 Angemon to the\nfield in the Compile Phase.",
	"Add +10 to all own Digimon's\nAP & HP.",
	"Increase one Digimon's \nHP by +30.",
	"Get 1 point of\nWhite S-Energy.",
	"Bring Patamon to the\nfield in Compile Phase.",
	"Return all non-blue Digimon\nback to each Hand.",
	"Get 1 of your opponent's\nDigimon from the field.",
	"Put a just drawn PG Card\ninto trash can.",
	"Return 1 Digimon back\nto its Hand.",
	"Get 1 point of\nBlue S-Energy.",
	"Bring Gomamon to the\nfield in Compile Phase.",
	" +50 to all own Green\nDigimon Card's AP & HP.",
	"Pick 1 Card from trash can\nto Hand. One time use.",
	"Get 2 points of\nGreen S-Energy.",
	" +20 to one Digimon's \nAP & HP.",
	"Get 1 point of\nGreen S-Energy.",
	"Bring Palmon to the\nfield in Compile Phase.",
	"60 damage points to all\nnon-red Digimon.",
	"Put all brown Digimon \ninto trash can.",
	"15 damage points to all\nDigimon.",
	"30 damage points to an\nopponent's Digimon.",
	"Get 1 point of\nRed S-Energy.",
	"Bring Goburimon to the\nfield in Compile Phase.",
	"Put all non-black Cards in\nopponent's Hand to trash.",
	"Pick 1 Card from Deck, \nadd it to Hand.",
	"Put one non-black Digimon \ninto trash can.",
	"Put one Card from opponent's\nHand into trash can.",
	"Get 1 point of\nBlack S-Energy.",
	"Bring out Devimon to the\nfield in Compile Phase.",
	"Put all Digimon into\ntrash can.",
	"Exchange the total AP and HP\nof both players.",
	"Pick 3 Cards from opponent's\nDeck to trash can.",
	"Put whole Hand in trash\nand draw 6 from the Deck.",
	"Reduce all S-Energy to zero.",
	"Return all Cards in trash \nback to the Deck.",
	"Make both players' Hands\nhave 3 Cards.",
	"Put 5 Cards from opponent's\nDeck into trash can.",
	"Reduce opponent's AP\nto zero.",
	"Bring a Digimon from Hand\nto the field in Compile Phase.",
	" +30 to one of Brown\nDigimon's AP & HP.",
	"Draw 2 Cards from Deck\nand add to Hand.",
	"Choose a Digimon from \nDeck and add to Hand.",
	"Choose a PG Card from\nDeck and add to Hand.",
	"Draw a Card from Deck and\nput 1 from Hand in trash.",
	"Put 2 Cards from opponent's\nDeck into trash can.",
	"30 damage points to 1 Brown\nDigimon of opponent.",
	"Put a just drawn Brown\nPG Card into trash can.",
	"Put 1 Brown Digimon from\nopponent's Hand into trash.",
	"Bring 2 Hagurumon to the\nfield in Compile Phase.",
	"Subtract 2 points from\nopponent's White S-Energy.",
	"Subtract 2 points from\nopponent's Blue S-Energy.",
	"Subtract 2 points from\nopponent's Green S-Energy.",
	"Subtract 2 points from\nopponent's Red S-Energy.",
	"Subtract 2 points from\nopponent's Black S-Energy.",
	"Return a Brown Digimon\nto Hand.",
	"AP +10 and HP -10 to\n1 Digimon.",
	"Put a Brown Digimon from\nfield into trash can.",
	"HP +10 to Digimon.",
	"AP +10 to Digimon.",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"AP & HP become 20x number\nof your Digimon in the field.",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"Add 10x the number of Cards\nin your Hand to AP & HP.",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"Add 20x the number of Cards\nin trash can to AP & HP.",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"AP & HP become 10x number\nof Digimon in all the fields.",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"a",
	"Add 10x the number of Cards\nin trash can to AP & HP.",
]
