entries = [
	"3/0.bin",
	"3/1.bin",
	"3/2.bin",
	"3/3.bin",
	"3/4.bin",
	"3/5.bin",
	"3/6.bin",
	"3/7.bin",
	"3/8.bin",
	"3/9.bin",
	"3/10.bin",
	"3/11.bin",
	"3/12.bin",
	"3/13.bin",
	"3/14.bin",
	"3/15.bin",
	"3/16.bin",
	"3/17.bin",
	"3/18.bin",
	"3/19.bin",
	"3/20.bin",
	"3/21.bin",
	"3/22.bin",
	"3/23.bin",
	"3/24.bin",
	"3/25.bin",
	"3/26.bin",
	"3/27.bin",
	"3/28.bin",
	"3/29.bin",
	"3/30.bin",
	"3/31.bin",
	"3/32.bin",
	"3/33.bin",
	"3/34.bin",
	"3/35.bin",
	"3/36.bin",
	"3/37.bin",
	"3/38.bin",
	"3/39.bin",
	"3/40.bin",
	"3/41.bin",
	"3/42.bin",
	"3/43.bin",
	"3/44.bin",
	"3/45.bin",
	"3/46.bin",
	"3/47.bin",
	"3/48.bin",
	"3/49.bin",
	"3/50.bin",
	"3/51.bin",
	"3/52.bin",
	"3/53.bin",
	"3/54.bin",
	"3/55.bin",
	"3/56.bin",
	"3/57.bin",
	"3/58.bin",
	"3/59.bin",
	"3/60.bin",
	"3/61.bin",
	"3/62.bin",
	"3/63.bin",
	"3/64.bin",
	"3/65.bin",
	"3/66.bin",
	"3/67.bin",
	"3/68.bin",
	"3/69.bin",
	"3/70.bin",
]
