strings = [
	"",
	"Lancia sacra",
	"Chiama Angemon",
	"Aura dorata",
	"Aura difensiva",
	"Energia bianca",
	"Chiama Patamon",
	"Ondata di marea",
	"Controlla parti",
	"Congelamento",
	"Annulla eclisse",
	"Energia blu",
	"Chiama Gomamon",
	"Controlla aura",
	"Ciclo ecologico",
	"Forza verde",
	"Energia bestie",
	"Energia verde",
	"Chiama Palmon",
	"Cannone vulcano",
	"Caos balenante",
	"Fiamme a raffica",
	"Cannone di fuoco",
	"Energia rossa",
	"Chiama Goburimon",
	"Tempesta oscura",
	"Occultamento",
	"Virus del caos",
	"Perfido hacker",
	"Energia nera",
	"Chiama Devimon",
	"Elimina Matrice",
	"Portale fortuna",
	"Portale miseria",
	"Brama d'accesso",
	"Anti-potere",
	"Carica vitale",
	"Cronoequilibrio",
	"Sala sicura",
	"Barriera totale",
	"Sconvolgimento",
	"Supermetallo",
	"Carica terminale",
	"Carica Digimon",
	"Carica programma",
	"Scambia carica",
	"Accesso illecito",
	"Blocca lancio",
	"Annulla ruota",
	"Polvere marcia",
	"Chiama Hagurumon",
	"Elimina bianco",
	"Elimina blu",
	"Elimina verde",
	"Elimina rosso",
	"Elimina nero",
	"Chiama annullo",
	"Energia furiosa",
	"Turba macchina",
	"Proteggi corazza",
	"Corazza assalto",
	"Imperialdramon-P",
	"GuardiAngemon",
	"WarGreymon",
	"ImperialdramonII",
	"Seraphimon",
	"Magnadramon",
	"Valkrymon",
	"PrinceMamemon",
	"RosemonII",
	"PaildramonII",
	"MagnaAngemon",
	"Angewomon",
	"Kyukimon",
	"Panjyamon",
	"Silphymon",
	"Knightmon",
	"MetalMamemon",
	"Mamemon",
	"Piximon",
	"Dinohumon",
	"Angemon",
	"Stingmon",
	"Gatomon",
	"Piddomon",
	"Apemon",
	"Centarumon",
	"Snimon",
	"Thundermon",
	"Unimon",
	"ShimaUnimon",
	"Ankylomon",
	"Gururumon",
	"Tortomon",
	"Zassomon",
	"Yanmamon",
	"Kotemon",
	"Armadillomon",
	"Psychemon",
	"Elecmon",
	"Patamon",
	"Wormmon",
	"Kunemon",
	"Salamon",
	"Cannondramon",
	"Sakuyamon",
	"Vikemon",
	"MetalSeadramon",
	"Pukumon",
	"SuperStarmon",
	"Preciomon",
	"Babamon",
	"MarineAngemon",
	"Zudomon",
	"MegaSeadramon",
	"Taomon",
	"Armormon",
	"BlueMeramon",
	"ShogunGekomon",
	"Scorpiomon",
	"Brachiomon",
	"WaruSeadramon",
	"Divermon",
	"Whamon",
	"Seadramon",
	"Kyubimon",
	"Hookmon",
	"IceDevimon",
	"Shellmon",
	"Ikkakumon",
	"Frigimon",
	"Ebidramon",
	"Icemon",
	"Mojyamon",
	"Ninjamon",
	"Starmon",
	"Coelamon",
	"Dolphmon",
	"Gekomon",
	"Monmon",
	"Renamon",
	"Gomamon",
	"SnowAgumon",
	"Gizamon",
	"Otamamon",
	"Crabmon",
	"Syakomon",
	"Omnimon II",
	"Marsmon",
	"MetalGarurumon",
	"H-Kabuterimon",
	"GranKuwagamon",
	"RosemonI",
	"KingEtemon",
	"MetalEtemon",
	"SaberLeomon",
	"MegaKabuterimon",
	"WereGarurumon",
	"GrapLeomon",
	"Okuwamon",
	"Lillymon",
	"Etemon",
	"Triceramon",
	"Cherrymon",
	"Blossomon",
	"Deramon",
	"Leomon",
	"Grizzmon",
	"Kabuterimon",
	"Garurumon",
	"Tuskmon",
	"Monochromon",
	"MoriShellmon",
	"Kuwagamon",
	"J-Mojyamon",
	"Togemon",
	"Flymon",
	"Saberdramon",
	"Dokugumon",
	"Kiwimon",
	"Woodmon",
	"Vegiemon",
	"Kumamon",
	"Gabumon",
	"Tentomon",
	"Palmon",
	"Betamon",
	"Kokuwamon",
	"Floramon",
	"Mushroomon",
	"Omnimon I",
	"Gallantmon",
	"Imperialdramon-F",
	"Imperialdramon I",
	"MegaGargomon",
	"Machinedramon",
	"Phoenixmon",
	"SkullMammothmon",
	"Gryphonmon",
	"Paildramon I",
	"MetalGreymon",
	"WarGrowlmon",
	"Garudamon",
	"Kimeramon",
	"MasterTyrannomon",
	"Gigadramon",
	"Megadramon",
	"MetalTyrannomon",
	"Mammothmon",
	"Greymon",
	"Growlmon",
	"ExVeemon",
	"Veedramon",
	"Airdramon",
	"Ogremon",
	"Minotarumon",
	"Fugamon",
	"Tyrannomon",
	"Aquilamon",
	"Meramon",
	"Birdramon",
	"Flarerizamon",
	"RedVegiemon",
	"Akatorimon",
	"SandYanmamon",
	"Agumon",
	"Veemon",
	"Guilmon",
	"Hawkmon",
	"Biyomon",
	"Goburimon",
	"Sharmamon",
	"Penguinmon",
	"Armageddemon",
	"VenomMyotismon",
	"Diaboromon",
	"MaloMyotismon",
	"Beelzemon",
	"Apokarimon",
	"Ghoulmon",
	"Piedmon",
	"Creepymon",
	"Myotismon",
	"Infermon",
	"Dragomon",
	"SkullSatamon",
	"SkullGreymon",
	"Mummymon",
	"Arukenimon",
	"LadyDevimon",
	"SkullMeramon",
	"WaruMonzaemon",
	"Devimon",
	"Kurisarimon",
	"Raremon",
	"MarineDevimon",
	"Musyamon",
	"Wizardmon",
	"DarkTyrannomon",
	"Devidramon",
	"Vilemon",
	"Hyogamon",
	"Darkrizamon",
	"Octomon",
	"Gesomon",
	"Soulmon",
	"Bakemon",
	"Roachmon",
	"DemiDevimon",
	"Gazimon",
	"Aruraumon",
	"Tsukaimon",
	"ModokiBetamon",
	"Tapirmon",
	"Candlemon",
	"Muchomon",
	"WarGreymon N",
	"Imperialdramon N",
	"MegaGargomon N",
	"Seraphimon N",
	"WarGrowlmon N",
	"KingNumemon N",
	"HiAndromon",
	"Boltmon",
	"Puppetmon",
	"Shakkoumon",
	"Andromon",
	"Giromon",
	"Datamon",
	"ExTyrannomon",
	"Monzaemon",
	"Digitamamon",
	"Vademon",
	"Garbagemon",
	"Meteormon",
	"Cyclonemon",
	"Rockmon",
	"Deltamon",
	"Guardromon",
	"Tankmon",
	"Clockmon",
	"MudFrigimon",
	"PlatinumSukamon",
	"BomberNanimon",
	"Drimogemon",
	"NiseDrimogemon",
	"Sukamon",
	"Geremon",
	"Kokatorimon",
	"Numemon",
	"ShellNumemon",
	"ClearAgumon",
	"ToyAgumon",
	"Gotsumon",
	"Hagurumon",
	"Calumon",
	"Impmon",
]
