strings = [
	"",
	"[name]Mr. Smith[name]Oin oink oooink![pause][clear]Oink, oin, ooink![pause][clear]Oin, ooink, ooin oi \noiin oinko![pause][clear]Oi oinioi oinoink\noinnk oin oinkk oi\n30000 BIT![pause]",
	"[name]Dealer Abel[name]Oioi!\n31000 BIT![pause]",
	"[name]Chief Milly[name]Oioi\n31500 \nBIT![pause]",
	"[name]RPG Fan Masao[name]Oin oi\n31900 BIT![pause]",
	"[name][player_name][name]Hmm. 32000 BIT\n...hmmm...[pause]",
]
